[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:postgres]
command=su - postgres -c "/usr/lib/postgresql/16/bin/postgres -D /var/lib/postgresql/16/main -c config_file=/etc/postgresql/16/main/postgresql.conf"
priority=10
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/postgres.log
stderr_logfile=/var/log/supervisor/postgres_err.log

[program:opensearch]
command=su - opensearch -c "/usr/share/opensearch/bin/opensearch"
priority=20
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/opensearch.log
stderr_logfile=/var/log/supervisor/opensearch_err.log

[program:data-prepper]
command=/usr/share/data-prepper/bin/data-prepper /usr/share/data-prepper/config/data-prepper-config.yaml /usr/share/data-prepper/pipelines/pipelines.yaml
priority=30
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/data-prepper.log
stderr_logfile=/var/log/supervisor/data-prepper_err.log

[program:fluent-bit]
command=/usr/bin/fluent-bit -c /etc/fluent-bit/fluent-bit.conf
priority=40
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/fluent-bit.log
stderr_logfile=/var/log/supervisor/fluent-bit_err.log

[program:manager]
command=/app/ResolutePulseManager --config /app/manager_config.json
directory=/app
priority=50
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/manager.log
stderr_logfile=/var/log/supervisor/manager_err.log

[program:opensearch-dashboards]
command=/usr/share/opensearch-dashboards/bin/opensearch-dashboards --allow-root
priority=60
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/opensearch-dashboards.log
stderr_logfile=/var/log/supervisor/opensearch-dashboards_err.log

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
priority=70
autostart=true
autorestart=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx_err.log
